config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "visitors#new"

  root to: "visitors#index"

  resources :visitors

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/visitor.rb
class Visitor < ApplicationRecord
  
  validates :name, :company, :purpose, presence: true
  
  scope :today, -> { where(:created_at => Time.now.beginning_of_day..Time.now.end_of_day) }
  scope :yesterday, -> { where(:created_at => 1.days.ago.beginning_of_day..1.days.ago.end_of_day) }
  scope :this_week, -> { where(:created_at => Time.now.beginning_of_week..Time.now.end_of_week) }
  scope :this_month, -> { where(:created_at => Time.now.beginning_of_month..Time.now.end_of_month) }
  scope :this_year, -> { where(:created_at => Time.now.beginning_of_year..Time.now.end_of_year) }
  scope :last_hour, -> { where(:created_at => 1.hour.ago..Time.now) }
  scope :last_week, -> { where(:created_at => 1.weeks.ago.beginning_of_week..1.weeks.ago.end_of_week) }
  scope :last_month, -> { where(:created_at => 1.months.ago.beginning_of_month..1.months.ago.end_of_month) }
  scope :last_year, -> { where(:created_at => 1.years.ago.beginning_of_year..1.years.ago.end_of_year) }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :set_visitor, only: [:show, :edit, :update, :destroy]

  def index
    @visitors = Visitor.today
  end

  def show
  end

  def new
    @visitor = Visitor.new
  end

  def edit
  end

  def create
    @visitor = Visitor.new(visitor_params)

    respond_to do |format|
      if @visitor.save
        format.html { redirect_to @visitor, notice: 'Visitor was successfully created.' }
        format.json { render :show, status: :created, location: @visitor }
      else
        format.html { render :new }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @visitor.update(visitor_params)
        format.html { redirect_to @visitor, notice: 'Visitor was successfully updated.' }
        format.json { render :show, status: :ok, location: @visitor }
      else
        format.html { render :edit }
        format.json { render json: @visitor.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @visitor.destroy
    respond_to do |format|
      format.html { redirect_to visitors_url, notice: 'Visitor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_visitor
      @visitor = Visitor.find(params[:id])
    end

    def visitor_params
      params.require(:visitor).permit(:name, :company, :purpose)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/layouts/_auth_links.html.erb
<% if user_signed_in? %>
  <li class="nav-item">
    <%= link_to current_user.email, edit_user_registration_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: "nav-link" %>
  </li>
<% else %>
  <li class="nav-item">
    <%= link_to 'Sign in', new_user_session_path, class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
  </li>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-12">
        <p>King Ocean Services</p>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Logbook", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/auth_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% if user_signed_in? %>
  <li class="nav-item">
    <%= link_to 'Visitors', visitors_path, class: "nav-link" %>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>King Ocean Logbook</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="apple-mobile-web-app-capable" content="yes">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <%# render "layouts/header" %>

      <div class="container-fluid">
        <%= yield %>
      </div>

      <%# render "layouts/footer" %>

  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/visitors/_form.html.erb
<%= form_with(model: visitor, local: true) do |form| %>
  <% if visitor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(visitor.errors.count, "error") %> prohibited this visitor from being saved:</h2>

      <ul>
      <% visitor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, class: 'col-form-label'%>
    <%= form.text_field :name, id: :visitor_name, class: 'form-control form-control-lg' %>
  </div>

  <div class="form-group">
    <%= form.label :company, class: 'col-form-label' %>
    <%= form.text_field :company, id: :visitor_company, class: 'form-control form-control-lg' %>
  </div>

  <div class="form-group">
    <%= form.label :purpose, class: 'col-form-label' %>
    <%= form.text_field :purpose, id: :visitor_purpose, class: 'form-control form-control-lg' %>
  </div>

  <%= form.submit class: 'btn btn-success btn-lg'%>
<% end %>

app/views/visitors/edit.html.erb
<div class="row mt-3 mb-3 align-items-center">
  <div class="col-auto mr-auto">
    <h1>Editing Visitor</h1>
  </div>
  <div class="col-auto">
    <%= link_to 'Show', @visitor, class: "btn btn-primary" %>
    <%= link_to 'Back', visitors_path, class: "btn btn-primary" %>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <%= render 'form', visitor: @visitor %>
  </div>
</div>

app/views/visitors/index.html.erb
<div class="row mt-3 mb-3 align-items-center">
  <div class="col-auto mr-auto">
    <h1>Visitors Log</h1>
  </div>
  <div class="col-auto">
    <%= link_to 'New Visitor', new_visitor_path, class: 'btn btn-success' %>
  </div>
</div>
<div class="row">
    <div class="col-sm-12">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Name</th>
          <th>Company</th>
          <th>Purpose</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @visitors.each do |visitor| %>
          <tr>
            <td><%= visitor.created_at.strftime("%d/%m/%Y %H:%M") %></td>
            <td><%= visitor.name %></td>
            <td><%= visitor.company %></td>
            <td><%= visitor.purpose %></td>
            <td><%= link_to 'Show', visitor, class: "btn btn-primary btn-sm" %></td>
            <td><%= link_to 'Edit', edit_visitor_path(visitor), class: "btn btn-info btn-sm"  %></td>
            <td><%= link_to 'Destroy', visitor, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm"  %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/visitors/new.html.erb
<div class="row mt-3 mb-3 align-items-center">
  <div class="col-auto mr-auto">
    <h1>New Visitor</h1>
  </div>
  <div class="col-auto">
    <%= link_to 'Back', visitors_path, class: 'btn btn-primary' %>
  </div>
</div>
<div class="row">
  <div class="col-sm-12">
    <%= render 'form', visitor: @visitor %>
  </div>
</div>

app/views/visitors/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-sm-12">
    <div class="card text-center">
      <div class="card-header">
        <strong>VISITOR</strong>
      </div>
      <div class="card-body">
        <h3>
          <%= @visitor.name %>
        </h3>
        <p>
          <%= @visitor.company %>
        </p>
        <p>
          <%= @visitor.created_at.strftime("%d/%m/%Y %H:%M") %>
        </p>
      </div>
      <div class="card-footer">
        <strong>KING OCEAN</strong>
      </div>
    </div>
  </div>
  <div class="col-sm-12 text-center mb-3 mt-3">
    <%= link_to 'Edit', edit_visitor_path(@visitor), class: "btn btn-info btn-sm d-print-none
" %>
    <%= link_to 'Back', visitors_path, class: 'btn btn-primary btn-sm d-print-none
' %>
  </div>
</div>